spring:
  application:
    name: employee_manager

  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.flyway: INFO
    org.springframework.boot.autoconfigure: INFO